jest.mock("../utils/log", () => ({
  actionLog: { info: jest.fn(), error: jest.fn() },
}));
jest.mock("./email", () => ({ sendEmail: jest.fn() }));
jest.mock("./messages", () => ({
  getAllUnsubscribeMethodsForVendor: jest.fn(),
  markVendorUnsubscribed: jest.fn(),
}));

import {
  getAllUnsubscribeMethodsForVendor,
  markVendorUnsubscribed,
} from "./messages";
import { sendEmail } from "./email";
import { unsubscribeVendor } from "./unsubscribe";

const getMethods = jest.mocked(getAllUnsubscribeMethodsForVendor);
const markUnsubscribed = jest.mocked(markVendorUnsubscribed);
const send = jest.mocked(sendEmail);

beforeEach(() => {
  jest.clearAllMocks();
});

describe("unsubscribeVendor", () => {
  it("posts an RFC 8058 request before marking the company unsubscribed", async () => {
    getMethods.mockReturnValue([{
      method: "rfc8058",
      url: "https://example.test/unsubscribe/token",
    }]);
    const request = jest.spyOn(global, "fetch").mockResolvedValue({
      ok: true,
      status: 204,
    } as Response);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "unsubscribed",
      method: "one_click",
    });
    expect(request).toHaveBeenCalledWith(
      "https://example.test/unsubscribe/token",
      {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: "List-Unsubscribe=One-Click",
      },
    );
    expect(markUnsubscribed).toHaveBeenCalledWith(42);
    request.mockRestore();
  });

  it("does not update Paperweight when a one-click request fails", async () => {
    getMethods.mockReturnValue([{
      method: "rfc8058",
      url: "https://example.test/unsubscribe/token",
    }]);
    const request = jest.spyOn(global, "fetch").mockResolvedValue({
      ok: false,
      status: 500,
    } as Response);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "failed",
      method: "one_click",
      error: "Server returned HTTP 500",
    });
    expect(markUnsubscribed).not.toHaveBeenCalled();
    request.mockRestore();
  });

  it("sends a mailto request before marking the company unsubscribed", async () => {
    getMethods.mockReturnValue([{
      method: "list-unsubscribe",
      url: "mailto:leave+token@example.test?subject=Remove%20me",
    }]);
    send.mockResolvedValue({ success: true });

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "unsubscribed",
      method: "email",
    });
    expect(send).toHaveBeenCalledWith(
      "leave+token@example.test",
      "Remove me",
      "This message was automatically generated by paperweight.email",
    );
    expect(markUnsubscribed).toHaveBeenCalledWith(42);
  });

  it("requires manual action for a browser unsubscribe method", async () => {
    getMethods.mockReturnValue([{
      method: "footer",
      url: "https://example.test/preferences/token",
    }]);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "manual_required",
      method: "browser",
      url: "https://example.test/preferences/token",
    });
    expect(send).not.toHaveBeenCalled();
    expect(markUnsubscribed).not.toHaveBeenCalled();
  });

  it("strips wrapping angle brackets from a browser unsubscribe URL", async () => {
    getMethods.mockReturnValue([{
      method: "list-unsubscribe",
      url: "<https://example.test/preferences/token>",
    }]);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "manual_required",
      method: "browser",
      url: "https://example.test/preferences/token",
    });
  });

  it.each([
    "file:///etc/passwd",
    "javascript:alert(1)",
    "ftp://example.test/unsub",
    "not a url",
    "https://",
    "",
  ])("does not return a non-http unsubscribe URL (%s)", async (url) => {
    getMethods.mockReturnValue([{
      method: "footer",
      url,
    }]);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "not_available",
    });
    expect(send).not.toHaveBeenCalled();
    expect(markUnsubscribed).not.toHaveBeenCalled();
  });

  it("does nothing when no unsubscribe method is available", async () => {
    getMethods.mockReturnValue([]);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "not_available",
    });
    expect(send).not.toHaveBeenCalled();
    expect(markUnsubscribed).not.toHaveBeenCalled();
  });
});
