// Parse the stored header JSON, tolerating both shapes we've written over time:
// the current lossless ordered [name, value][] array (duplicates preserved) and
// the legacy { name: value } object (rows synced before losslessization). A row
// only converts to the array shape when a body-bearing fetch re-visits it, and
// free-tier accounts never re-fetch their older mail — so the legacy shape is
// permanent and every reader must accept both.
export function parseHeaderPairs(
  headersJson: string | null | undefined,
): Array<[string, string]> {
  if (!headersJson) return [];
  try {
    const parsed = JSON.parse(headersJson) as unknown;
    if (Array.isArray(parsed)) {
      const pairs: Array<[string, string]> = [];
      for (const entry of parsed) {
        if (
          Array.isArray(entry) &&
          typeof entry[0] === "string" &&
          typeof entry[1] === "string"
        ) {
          pairs.push([entry[0], entry[1]]);
        }
      }
      return pairs;
    }
    if (parsed && typeof parsed === "object") {
      return Object.entries(parsed as Record<string, unknown>).filter(
        (e): e is [string, string] => typeof e[1] === "string",
      );
    }
    return [];
  } catch {
    return [];
  }
}

// Ordered [name, value] pairs -> the engine's RawMessage.headers shape. Repeats
// of one header collapse into an array so nothing is lost (the engine reads all
// List-Unsubscribe and DKIM-Signature values, not just the first). Both callers
// start from pairs: providers hold them at parse time, and stored rows get them
// back from parseHeaderPairs.
export function headerRecord(
  pairs: Array<[string, string]>,
): Record<string, string | string[]> {
  const headers: Record<string, string | string[]> = {};
  for (const [name, value] of pairs) {
    const existing = headers[name];
    if (existing === undefined) headers[name] = value;
    else if (Array.isArray(existing)) existing.push(value);
    else headers[name] = [existing, value];
  }
  return headers;
}

const COMPOUND_TLDS = new Set([
  "co.uk", "org.uk", "me.uk", "ac.uk",
  "com.au", "net.au", "org.au",
  "co.nz", "co.za", "co.in", "co.jp", "co.kr",
  "com.br", "com.mx", "com.ar", "com.co",
  "com.tr", "com.sg", "com.hk", "com.tw",
]);

export function getRootDomain(domain: string): string {
  const parts = domain.split(".");
  if (parts.length <= 2) return domain;
  const lastTwo = parts.slice(-2).join(".");
  if (COMPOUND_TLDS.has(lastTwo)) {
    return parts.slice(-3).join(".");
  }
  return lastTwo;
}

// Default body for unsubscribe emails generated by Paperweight when the mailto:
// URL doesn't supply one. Adds attribution so the message is recognizable in the
// user's Sent folder and on the receiving side. Plain text — most unsubscribe
// addresses don't render HTML, and recipient parsers ignore the body anyway.
export const PAPERWEIGHT_UNSUB_BODY =
  "This message was automatically generated by paperweight.email";

// RFC 6068 mailto: parser. URLSearchParams treats "+" as space, but per RFC 6068
// "+" must remain literal (only %20 is space). Hand-rolled split + decodeURIComponent
// preserves the literal "+" that some unsubscribe tokens rely on.
export function parseMailto(url: string): { to: string; subject: string; body: string } {
  const rest = url.replace(/^mailto:/i, "");
  const qIdx = rest.indexOf("?");
  const pathPart = qIdx === -1 ? rest : rest.slice(0, qIdx);
  const queryPart = qIdx === -1 ? "" : rest.slice(qIdx + 1);

  const decode = (s: string): string => {
    try {
      return decodeURIComponent(s);
    } catch {
      return s;
    }
  };

  const params = new Map<string, string>();
  if (queryPart) {
    for (const pair of queryPart.split("&")) {
      if (!pair) continue;
      const eq = pair.indexOf("=");
      const key = decode(eq === -1 ? pair : pair.slice(0, eq)).toLowerCase();
      const val = eq === -1 ? "" : decode(pair.slice(eq + 1));
      params.set(key, val);
    }
  }

  return {
    to: params.get("to") || decode(pathPart),
    subject: params.get("subject") || "",
    body: params.get("body") || "",
  };
}
