name: Build Installers

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build macOS installer
        run: pnpm dist:mac

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: macos-installers
          path: dist/*.dmg
          archive: false

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build Linux installer
        run: pnpm dist:linux

      - name: Upload AppImage
        uses: actions/upload-artifact@v7
        with:
          name: linux-appimage
          path: dist/*.AppImage
          archive: false
      - name: Upload deb
        uses: actions/upload-artifact@v7
        with:
          name: linux-deb
          path: dist/*.deb
          archive: false

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build Windows installer
        run: pnpm dist:win

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: windows-installers
          path: dist/*.exe
          archive: false
